"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FALLBACKS = void 0;

var positions = _interopRequireWildcard(require("./positions"));

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {}; if (desc.get || desc.set) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } } newObj.default = obj; return newObj; } }

function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread(); }

function _nonIterableSpread() { throw new TypeError("Invalid attempt to spread non-iterable instance"); }

function _iterableToArray(iter) { if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter); }

function _arrayWithoutHoles(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = new Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } }

/**
 * This determins the order in which to check whether the pop will fit
 * on the screen or not, if the provided position doesn't fit, this order
 * will be used starting at the next position.
 *
 * Structure of a position is:
 * [
 *   { vertical: string; horizontal: string }, // anchor
 *   { vertical: string; horizontal: string }, // pop
 *   [ ...Fallback positions ]
 * ]
 */
var FALLBACKS = [
/**
 * All vertical && horizontal non-centered
 * =========================
 */
// Top/Top
[].concat(_toConsumableArray(positions.TOP_RIGHT_TOP_LEFT), [[positions.TOP_LEFT_TOP_RIGHT, positions.BOTTOM_RIGHT_BOTTOM_LEFT, positions.BOTTOM_LEFT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_TOP_RIGHT), [[positions.TOP_RIGHT_TOP_LEFT, positions.BOTTOM_LEFT_BOTTOM_RIGHT, positions.BOTTOM_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_TOP_LEFT), [[positions.TOP_RIGHT_TOP_RIGHT, positions.BOTTOM_LEFT_BOTTOM_LEFT, positions.BOTTOM_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_TOP_RIGHT), [[positions.TOP_LEFT_TOP_LEFT, positions.BOTTOM_RIGHT_BOTTOM_RIGHT, positions.BOTTOM_LEFT_BOTTOM_LEFT]]), // Top/Bottom
[].concat(_toConsumableArray(positions.TOP_RIGHT_BOTTOM_LEFT), [[positions.TOP_LEFT_BOTTOM_RIGHT, positions.BOTTOM_RIGHT_TOP_LEFT, positions.BOTTOM_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_BOTTOM_RIGHT), [[positions.TOP_RIGHT_BOTTOM_LEFT, positions.BOTTOM_LEFT_TOP_RIGHT, positions.BOTTOM_RIGHT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_BOTTOM_LEFT), [[positions.TOP_RIGHT_BOTTOM_RIGHT, positions.BOTTOM_LEFT_TOP_LEFT, positions.BOTTOM_RIGHT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_BOTTOM_RIGHT), [[positions.TOP_LEFT_BOTTOM_LEFT, positions.BOTTOM_RIGHT_TOP_RIGHT, positions.BOTTOM_LEFT_TOP_LEFT]]), // Bottom/Top
[].concat(_toConsumableArray(positions.BOTTOM_RIGHT_TOP_LEFT), [[positions.BOTTOM_LEFT_TOP_RIGHT, positions.TOP_RIGHT_BOTTOM_LEFT, positions.TOP_LEFT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_TOP_RIGHT), [[positions.BOTTOM_RIGHT_TOP_LEFT, positions.TOP_LEFT_BOTTOM_RIGHT, positions.TOP_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_TOP_LEFT), [[positions.BOTTOM_RIGHT_TOP_RIGHT, positions.TOP_LEFT_BOTTOM_LEFT, positions.TOP_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_TOP_RIGHT), [[positions.BOTTOM_LEFT_TOP_LEFT, positions.TOP_RIGHT_BOTTOM_RIGHT, positions.TOP_LEFT_BOTTOM_LEFT]]),
/**
 * Bottom/Bottom
 * =============
 */
[].concat(_toConsumableArray(positions.BOTTOM_RIGHT_BOTTOM_LEFT), [[positions.BOTTOM_LEFT_BOTTOM_RIGHT, positions.TOP_RIGHT_TOP_LEFT, positions.TOP_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_BOTTOM_RIGHT), [[positions.BOTTOM_RIGHT_BOTTOM_LEFT, positions.TOP_LEFT_TOP_RIGHT, positions.TOP_RIGHT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_BOTTOM_LEFT), [[positions.BOTTOM_RIGHT_BOTTOM_RIGHT, positions.TOP_LEFT_TOP_LEFT, positions.TOP_RIGHT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_BOTTOM_RIGHT), [[positions.BOTTOM_LEFT_BOTTOM_LEFT, positions.TOP_RIGHT_TOP_RIGHT, positions.TOP_LEFT_TOP_LEFT]]),
/**
 * all horizontal centered
 * =====================
 */
// Top/Top
[].concat(_toConsumableArray(positions.TOP_LEFT_TOP_CENTER), [[positions.TOP_RIGHT_TOP_CENTER, positions.TOP_LEFT_BOTTOM_CENTER, positions.TOP_RIGHT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.TOP_LEFT_TOP_RIGHT), [[positions.TOP_RIGHT_TOP_LEFT, positions.BOTTOM_LEFT_BOTTOM_RIGHT, positions.BOTTOM_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_TOP_LEFT), [[positions.TOP_RIGHT_TOP_RIGHT, positions.BOTTOM_LEFT_BOTTOM_LEFT, positions.BOTTOM_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_TOP_CENTER), [[positions.TOP_LEFT_TOP_CENTER, positions.TOP_RIGHT_BOTTOM_CENTER, positions.TOP_LEFT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_TOP_RIGHT), [[positions.TOP_LEFT_TOP_LEFT, positions.BOTTOM_LEFT_BOTTOM_LEFT, positions.BOTTOM_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_TOP_LEFT), [[positions.TOP_LEFT_TOP_RIGHT, positions.BOTTOM_RIGHT_BOTTOM_LEFT, positions.BOTTOM_LEFT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_TOP_CENTER), [[positions.BOTTOM_CENTER_BOTTOM_CENTER, positions.TOP_CENTER_BOTTOM_CENTER, positions.BOTTOM_CENTER_TOP_CENTER]]), [].concat(_toConsumableArray(positions.TOP_CENTER_TOP_RIGHT), [[positions.TOP_CENTER_TOP_LEFT, positions.BOTTOM_CENTER_BOTTOM_RIGHT, positions.BOTTOM_CENTER_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_TOP_LEFT), [[positions.TOP_CENTER_TOP_RIGHT, positions.BOTTOM_CENTER_BOTTOM_RIGHT, positions.BOTTOM_CENTER_BOTTOM_LEFT]]), // Top/Bottom
[].concat(_toConsumableArray(positions.TOP_LEFT_BOTTOM_CENTER), [[positions.TOP_RIGHT_BOTTOM_CENTER, positions.TOP_LEFT_TOP_CENTER, positions.TOP_RIGHT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.TOP_LEFT_BOTTOM_RIGHT), [[positions.TOP_RIGHT_BOTTOM_LEFT, positions.BOTTOM_LEFT_BOTTOM_RIGHT, positions.BOTTOM_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_BOTTOM_LEFT), [[positions.TOP_RIGHT_BOTTOM_RIGHT, positions.BOTTOM_LEFT_TOP_LEFT, positions.BOTTOM_RIGHT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_BOTTOM_CENTER), [[positions.TOP_LEFT_BOTTOM_CENTER, positions.TOP_RIGHT_TOP_CENTER, positions.TOP_LEFT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_BOTTOM_RIGHT), [[positions.TOP_LEFT_BOTTOM_LEFT, positions.BOTTOM_RIGHT_TOP_RIGHT, positions.BOTTOM_LEFT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_BOTTOM_LEFT), [[positions.TOP_LEFT_BOTTOM_RIGHT, positions.BOTTOM_RIGHT_TOP_LEFT, positions.BOTTOM_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_BOTTOM_CENTER), [[positions.TOP_CENTER_TOP_CENTER, positions.BOTTOM_CENTER_TOP_CENTER, positions.BOTTOM_CENTER_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.TOP_CENTER_BOTTOM_RIGHT), [[positions.TOP_CENTER_BOTTOM_LEFT, positions.BOTTOM_CENTER_TOP_LEFT, positions.BOTTOM_CENTER_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_BOTTOM_LEFT), [[positions.TOP_CENTER_BOTTOM_RIGHT, positions.BOTTOM_CENTER_TOP_RIGHT, positions.BOTTOM_CENTER_TOP_LEFT]]), // Bottom/Bottom
[].concat(_toConsumableArray(positions.BOTTOM_LEFT_BOTTOM_CENTER), [[positions.BOTTOM_RIGHT_BOTTOM_CENTER, positions.TOP_LEFT_TOP_CENTER, positions.TOP_RIGHT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_BOTTOM_RIGHT), [[positions.BOTTOM_RIGHT_BOTTOM_LEFT, positions.TOP_RIGHT_TOP_LEFT, positions.TOP_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_BOTTOM_LEFT), [[positions.BOTTOM_RIGHT_BOTTOM_RIGHT, positions.TOP_LEFT_TOP_LEFT, positions.TOP_RIGHT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_BOTTOM_CENTER), [[positions.BOTTOM_LEFT_BOTTOM_CENTER, positions.TOP_RIGHT_TOP_CENTER, positions.TOP_LEFT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_BOTTOM_RIGHT), [[positions.BOTTOM_LEFT_BOTTOM_LEFT, positions.TOP_RIGHT_TOP_RIGHT, positions.TOP_LEFT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_BOTTOM_LEFT), [[positions.BOTTOM_LEFT_BOTTOM_RIGHT, positions.TOP_RIGHT_TOP_LEFT, positions.TOP_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_BOTTOM_CENTER), [[positions.TOP_CENTER_TOP_CENTER, positions.BOTTOM_CENTER_TOP_CENTER, positions.TOP_CENTER_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_BOTTOM_RIGHT), [[positions.BOTTOM_CENTER_BOTTOM_LEFT, positions.TOP_CENTER_TOP_RIGHT, positions.TOP_CENTER_TOP_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_BOTTOM_LEFT), [[positions.BOTTOM_CENTER_BOTTOM_RIGHT, positions.TOP_CENTER_TOP_LEFT, positions.TOP_CENTER_TOP_RIGHT]]), // Bottom/Top
[].concat(_toConsumableArray(positions.BOTTOM_CENTER_TOP_CENTER), [[positions.TOP_CENTER_BOTTOM_CENTER, positions.BOTTOM_CENTER_BOTTOM_CENTER, positions.TOP_CENTER_TOP_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_TOP_RIGHT), [[positions.BOTTOM_CENTER_TOP_LEFT, positions.TOP_CENTER_BOTTOM_RIGHT, positions.TOP_CENTER_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_TOP_LEFT), [[positions.BOTTOM_CENTER_TOP_RIGHT, positions.TOP_CENTER_BOTTOM_LEFT, positions.TOP_CENTER_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_TOP_CENTER), [[positions.BOTTOM_RIGHT_TOP_CENTER, positions.TOP_LEFT_BOTTOM_CENTER, positions.TOP_RIGHT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_TOP_RIGHT), [[positions.BOTTOM_RIGHT_TOP_LEFT, positions.TOP_LEFT_BOTTOM_RIGHT, positions.TOP_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_TOP_LEFT), [[positions.BOTTOM_RIGHT_TOP_RIGHT, positions.TOP_LEFT_BOTTOM_LEFT, positions.TOP_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_TOP_CENTER), [[positions.BOTTOM_LEFT_TOP_CENTER, positions.TOP_RIGHT_BOTTOM_CENTER, positions.TOP_LEFT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_TOP_RIGHT), [[positions.BOTTOM_CENTER_TOP_LEFT, positions.TOP_CENTER_BOTTOM_RIGHT, positions.TOP_CENTER_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_TOP_LEFT), [[positions.BOTTOM_CENTER_TOP_RIGHT, positions.TOP_CENTER_TOP_LEFT, positions.TOP_CENTER_TOP_RIGHT]]),
/**
 * all vertical centered
 * =====================
 */
// Top/Center
[].concat(_toConsumableArray(positions.TOP_LEFT_CENTER_RIGHT), [[positions.TOP_RIGHT_CENTER_LEFT, positions.BOTTOM_LEFT_CENTER_RIGHT, positions.BOTTOM_RIGHT_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_CENTER_LEFT), [[positions.TOP_RIGHT_CENTER_RIGHT, positions.BOTTOM_LEFT_CENTER_LEFT, positions.BOTTOM_RIGHT_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_LEFT_CENTER_CENTER), [[positions.TOP_RIGHT_CENTER_CENTER, positions.BOTTOM_LEFT_CENTER_CENTER, positions.BOTTOM_RIGHT_CENTER_CENTER]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_CENTER_RIGHT), [[positions.TOP_LEFT_CENTER_LEFT, positions.BOTTOM_RIGHT_CENTER_RIGHT, positions.BOTTOM_LEFT_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_CENTER_LEFT), [[positions.TOP_LEFT_CENTER_RIGHT, positions.BOTTOM_RIGHT_CENTER_LEFT, positions.BOTTOM_LEFT_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_RIGHT_CENTER_CENTER), [[positions.TOP_LEFT_CENTER_CENTER, positions.BOTTOM_RIGHT_CENTER_CENTER, positions.BOTTOM_LEFT_CENTER_CENTER]]), [].concat(_toConsumableArray(positions.TOP_CENTER_CENTER_LEFT), [[positions.TOP_CENTER_CENTER_RIGHT, positions.BOTTOM_CENTER_CENTER_LEFT, positions.BOTTOM_CENTER_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_CENTER_RIGHT), [[positions.TOP_CENTER_CENTER_LEFT, positions.BOTTOM_CENTER_CENTER_RIGHT, positions.BOTTOM_CENTER_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.TOP_CENTER_CENTER_CENTER), [[positions.BOTTOM_CENTER_CENTER_CENTER, positions.CENTER_RIGHT_CENTER_CENTER, positions.CENTER_LEFT_CENTER_CENTER]]), // Bottom/Center
[].concat(_toConsumableArray(positions.BOTTOM_LEFT_CENTER_RIGHT), [[positions.BOTTOM_RIGHT_CENTER_LEFT, positions.TOP_LEFT_CENTER_RIGHT, positions.TOP_RIGHT_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_CENTER_LEFT), [[positions.BOTTOM_RIGHT_CENTER_RIGHT, positions.TOP_LEFT_CENTER_LEFT, positions.TOP_RIGHT_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_LEFT_CENTER_CENTER), [[positions.BOTTOM_RIGHT_CENTER_CENTER, positions.TOP_LEFT_CENTER_CENTER, positions.TOP_RIGHT_CENTER_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_CENTER_RIGHT), [[positions.BOTTOM_LEFT_CENTER_LEFT, positions.TOP_RIGHT_CENTER_RIGHT, positions.TOP_LEFT_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_CENTER_LEFT), [[positions.BOTTOM_LEFT_CENTER_RIGHT, positions.TOP_RIGHT_CENTER_LEFT, positions.TOP_LEFT_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_RIGHT_CENTER_CENTER), [[positions.BOTTOM_LEFT_CENTER_CENTER, positions.TOP_RIGHT_CENTER_CENTER, positions.TOP_LEFT_CENTER_CENTER]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_CENTER_LEFT), [[positions.BOTTOM_CENTER_CENTER_RIGHT, positions.TOP_CENTER_CENTER_LEFT, positions.TOP_CENTER_CENTER_RIGHT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_CENTER_RIGHT), [[positions.BOTTOM_CENTER_CENTER_LEFT, positions.TOP_CENTER_CENTER_RIGHT, positions.TOP_CENTER_CENTER_LEFT]]), [].concat(_toConsumableArray(positions.BOTTOM_CENTER_CENTER_CENTER), [[positions.TOP_CENTER_CENTER_CENTER, positions.LEFT_CENTER_CENTER_CENTER, positions.RIGHT_CENTER_CENTER_CENTER]]), // Center/Top
[].concat(_toConsumableArray(positions.CENTER_RIGHT_TOP_LEFT), [[positions.CENTER_LEFT_TOP_RIGHT, positions.CENTER_RIGHT_BOTTOM_LEFT, positions.CENTER_LEFT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_RIGHT_TOP_RIGHT), [[positions.CENTER_LEFT_TOP_LEFT, positions.CENTER_RIGHT_BOTTOM_RIGHT, positions.CENTER_LEFT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_RIGHT_TOP_CENTER), [[positions.CENTER_LEFT_TOP_CENTER, positions.CENTER_RIGHT_BOTTOM_CENTER, positions.CENTER_LEFT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_TOP_LEFT), [[positions.CENTER_RIGHT_TOP_RIGHT, positions.CENTER_LEFT_BOTTOM_LEFT, positions.CENTER_RIGHT_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_TOP_RIGHT), [[positions.CENTER_RIGHT_TOP_LEFT, positions.CENTER_LEFT_BOTTOM_RIGHT, positions.CENTER_RIGHT_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_TOP_CENTER), [[positions.CENTER_RIGHT_TOP_CENTER, positions.CENTER_LEFT_BOTTOM_CENTER, positions.CENTER_RIGHT_BOTTOM_CENTER]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_TOP_LEFT), [[positions.CENTER_CENTER_TOP_RIGHT, positions.CENTER_CENTER_BOTTOM_LEFT, positions.CENTER_CENTER_BOTTOM_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_TOP_RIGHT), [[positions.CENTER_CENTER_TOP_LEFT, positions.CENTER_CENTER_BOTTOM_RIGHT, positions.CENTER_CENTER_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_TOP_CENTER), [[positions.CENTER_CENTER_BOTTOM_CENTER, positions.CENTER_CENTER_CENTER_RIGHT, positions.CENTER_CENTER_CENTER_LEFT]]), // Center/Bottom
[].concat(_toConsumableArray(positions.CENTER_RIGHT_BOTTOM_LEFT), [[positions.CENTER_LEFT_BOTTOM_RIGHT, positions.CENTER_RIGHT_TOP_LEFT, positions.CENTER_LEFT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_RIGHT_BOTTOM_RIGHT), [[positions.CENTER_LEFT_BOTTOM_LEFT, positions.CENTER_RIGHT_TOP_RIGHT, positions.CENTER_LEFT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_RIGHT_BOTTOM_CENTER), [[positions.CENTER_LEFT_BOTTOM_CENTER, positions.CENTER_RIGHT_TOP_CENTER, positions.CENTER_LEFT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_BOTTOM_LEFT), [[positions.CENTER_RIGHT_BOTTOM_RIGHT, positions.CENTER_LEFT_TOP_LEFT, positions.CENTER_RIGHT_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_BOTTOM_RIGHT), [[positions.CENTER_RIGHT_BOTTOM_LEFT < positions.CENTER_LEFT_TOP_RIGHT, positions.CENTER_RIGHT_TOP_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_LEFT_BOTTOM_CENTER), [[positions.CENTER_RIGHT_BOTTOM_CENTER, positions.CENTER_LEFT_TOP_CENTER, positions.CENTER_RIGHT_TOP_CENTER]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_BOTTOM_LEFT), [[positions.CENTER_CENTER_BOTTOM_RIGHT, positions.CENTER_CENTER_TOP_LEFT, positions.CENTER_CENTER_TOP_RIGHT]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_BOTTOM_RIGHT), [[positions.CENTER_CENTER_BOTTOM_LEFT, positions.CENTER_CENTER_TOP_RIGHT, positions.CENTER_CENTER_BOTTOM_LEFT]]), [].concat(_toConsumableArray(positions.CENTER_CENTER_BOTTOM_CENTER), [[positions.CENTER_CENTER_TOP_CENTER, positions.CENTER_CENTER_RIGHT_CENTER, positions.CENTER_CENTER_LEFT_CENTER]])];
exports.FALLBACKS = FALLBACKS;